WSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Clojure Lambda with plain Ring and Compojure

Resources:
  SimpleRingHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.github.mbroughani81.test.SimpleRingHandler
      Runtime: java8.al2
      MemorySize: 1024
      Timeout: 30
      CodeUri: ./target/openwhisk-app-0.1.0-SNAPSHOT-standalone.jar
      Events:
        SayHello:
          Type: Api
          Properties:
            Path: /helloRing/{helloId}
            Method: get
  CreateSubmit:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.github.mbroughani81.create_submit.RequestHandler
      Runtime: java8.al2
      MemorySize: 1024
      Timeout: 30
      CodeUri: ./target/openwhisk-app-0.1.0-SNAPSHOT-standalone.jar
      Events:
        SayHello:
          Type: Api
          Properties:
            Path: /create_submit
            Method: get
